###
GET http://localhost:5001/


###
POST http://localhost:8001/api/auth/login
Content-Type: application/json

{
    "email":"itssujan167@gmail.com",
    "password":"password123"
}

###
POST http://localhost:8001/exchange 
Content-Type: application/json"

{
    "message": "Test message"
}

###
GET http://localhost:8010/api/messages/processed-messages?email=itssujan167@gmail.com
Content-Type: application/json"

###
POST http://localhost:8010/api/messages/get-session-id
Content-Type: application/json

{
    "loggedInEmail": "itssujan167@gmail.com"
}


###
GET http://localhost:8010/auth/google